<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\Models\Record;
use App\Models\User;

class CreateRecordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $records = [
            [
                'user_id' => 5,
                'birth_date' => Carbon::parse('2005-01-15'),
                'age' => 18,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'address' => '51 Bonifacio Street, Quezon City',
                'mobile_number' => '0974-923-4570',
                'contact_person' => 'Jane Doe',
                'contact_person_number' => '0998-765-4321',
            ],
            [
                'user_id' => 6,
                'birth_date' => Carbon::parse('2004-03-15'),
                'age' => 17,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '2772 Roxas Boulevard, Pasay City',
                'mobile_number' => '0927-729-4643',
                'contact_person' => 'Sherwin Parker',
                'contact_person_number' => '0987-654-321',
            ],
            [
                'user_id' => 7,
                'birth_date' => Carbon::parse('1990-01-01'),
                'age' => 33,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'address' => '123 Main Street, City, Country',
                'mobile_number' => '0941-215-7765',
                'contact_person' => 'John Doe',
                'contact_person_number' => '0987-654-3210',
            ],
            [
                'user_id' => 8,
                'birth_date' => Carbon::parse('2005-08-10'),
                'age' => 17,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '123 ABC Street, Cityville',
                'mobile_number' => '0935-765-0839',
                'contact_person' => 'Ligaya Scovgachn',
                'contact_person_number' => '0987-654-3210',
            ],
            [
                'user_id' => 9,
                'birth_date' => Carbon::parse('1996-06-22'),
                'age' => 27,
                'sex' => 'Male',
                'civil_status' => 'Married',
                'address' => '321 YZA Street, Villagedale',
                'mobile_number' => '0987-654-3210',
                'contact_person' => 'Sophia Brown',
                'contact_person_number' => '0919-876-5432',
            ],
            [
                'user_id' => 10,
                'birth_date' => Carbon::parse('2000-08-03'),
                'age' => 22,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '654 BCD Street, Towndale',
                'mobile_number' => '0912-345-6789',
                'contact_person' => 'James Johnson',
                'contact_person_number' => '0987-654-3210',
            ],
            [
                'user_id' => 11,
                'birth_date' => Carbon::parse('1990-03-15'),
                'age' => 33,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '456 XYZ Street, Townsville',
                'mobile_number' => '0912-345-6789',
                'contact_person' => 'John Doe',
                'contact_person_number' => '0987-654-3210',
            ],    
            [
                'user_id' => 12,
                'birth_date' => Carbon::parse('1985-11-25'),
                'age' => 37,
                'sex' => 'Male',
                'civil_status' => 'Married',
                'address' => '789 PQR Street, Villagetown',
                'mobile_number' => '0919-876-5432',
                'contact_person' => 'Jane Smith',
                'contact_person_number' => '0912-345-6789',
            ],
            [
                'user_id' => 13,
                'birth_date' => Carbon::parse('2002-07-05'),
                'age' => 20,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'address' => '321 DEF Street, Citytown',
                'mobile_number' => '0987-654-3210',
                'contact_person' => 'Sarah Johnson',
                'contact_person_number' => '0919-876-5432',
            ],
            [
                'user_id' => 14,
                'birth_date' => Carbon::parse('1998-09-12'),
                'age' => 24,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '654 GHI Street, Villageton',
                'mobile_number' => '0912-345-6789',
                'contact_person' => 'Michael Brown',
                'contact_person_number' => '0987-654-3210',
            ],
            [
                'user_id' => 15,
                'birth_date' => Carbon::parse('1995-02-28'),
                'age' => 28,
                'sex' => 'Male',
                'civil_status' => 'Married',
                'address' => '987 JKL Street, Towndale',
                'mobile_number' => '0919-876-5432',
                'contact_person' => 'Emily Davis',
                'contact_person_number' => '0912-345-6789',
            ],                
            [
                'user_id' => 16,
                'birth_date' => Carbon::parse('1993-12-07'),
                'age' => 29,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '456 MNO Street, Cityville',
                'mobile_number' => '0987-654-3210',
                'contact_person' => 'Christopher Wilson',
                'contact_person_number' => '0919-876-5432',
            ],                
            [
                'user_id' => 17,
                'birth_date' => Carbon::parse('1999-04-18'),
                'age' => 24,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'address' => '789 STU Street, Townberg',
                'mobile_number' => '0912-345-6789',
                'contact_person' => 'Olivia Johnson',
                'contact_person_number' => '0987-654-3210',
            ],                
            [
                'user_id' => 18,
                'birth_date' => Carbon::parse('2001-10-30'),
                'age' => 21,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '123 VWX Street, Citytown',
                'mobile_number' => '0919-876-5432',
                'contact_person' => 'David Smith',
                'contact_person_number' => '0912-345-6789',
            ],            
            [
                'user_id' => 19,
                'birth_date' => Carbon::parse('1997-01-14'),
                'age' => 26,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'address' => '123 CDE Street, Cityville',
                'mobile_number' => '0912-345-6789',
                'contact_person' => 'Emma Wilson',
                'contact_person_number' => '0987-654-3210',
            ],
            [
                'user_id' => 20,
                'birth_date' => Carbon::parse('1994-09-27'),
                'age' => 28,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '456 EFG Street, Townsville',
                'mobile_number' => '0919-876-5432',
                'contact_person' => 'William Johnson',
                'contact_person_number' => '0912-345-6789',
            ],
            [
                'user_id' => 21,
                'birth_date' => Carbon::parse('2003-03-08'),
                'age' => 20,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'address' => '789 GHI Street, Villagetown',
                'mobile_number' => '0987-654-3210',
                'contact_person' => 'Sophie Davis',
                'contact_person_number' => '0919-876-5432',
            ],
            [
                'user_id' => 22,
                'birth_date' => Carbon::parse('1999-05-16'),
                'age' => 24,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '321 IJK Street, Citytown',
                'mobile_number' => '0912-345-6789',
                'contact_person' => 'Noah Smith',
                'contact_person_number' => '0987-654-3210',
            ],                
            [
                'user_id' => 23,
                'birth_date' => Carbon::parse('1996-12-31'),
                'age' => 26,
                'sex' => 'Male',
                'civil_status' => 'Married',
                'address' => '654 KLM Street, Villageton',
                'mobile_number' => '0919-876-5432',
                'contact_person' => 'Ava Johnson',
                'contact_person_number' => '0912-345-6789',
            ],                
            [
                'user_id' => 24,
                'birth_date' => Carbon::parse('1992-04-22'),
                'age' => 31,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '987 MNO Street, Towndale',
                'mobile_number' => '0987-654-3210',
                'contact_person' => 'Liam Brown',
                'contact_person_number' => '0919-876-5432',
            ],                
            [
                'user_id' => 25,
                'birth_date' => Carbon::parse('1998-08-11'),
                'age' => 24,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'address' => '123 PQR Street, Townberg',
                'mobile_number' => '0912-345-6789',
                'contact_person' => 'Isabella Davis',
                'contact_person_number' => '0987-654-3210',
            ],                
            [
                'user_id' => 26,
                'birth_date' => Carbon::parse('2000-02-03'),
                'age' => 23,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '456 STU Street, Citytown',
                'mobile_number' => '0919-876-5432',
                'contact_person' => 'Mason Wilson',
                'contact_person_number' => '0912-345-6789',
            ],                
            [
                'user_id' => 27,
                'birth_date' => Carbon::parse('1995-06-25'),
                'age' => 27,
                'sex' => 'Male',
                'civil_status' => 'Married',
                'address' => '789 UVW Street, Villagedale',
                'mobile_number' => '0987-654-3210',
                'contact_person' => 'Charlotte Brown',
                'contact_person_number' => '0919-876-5432',
            ],                
            [
                'user_id' => 28,
                'birth_date' => Carbon::parse('2001-09-07'),
                'age' => 21,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '321 XYZ Street, Towndale',
                'mobile_number' => '0912-345-6789',
                'contact_person' => 'Henry Johnson',
                'contact_person_number' => '0987-654-3210',
            ],                
            [
                'user_id' => 29,
                'birth_date' => Carbon::parse('1993-07-18'),
                'age' => 30,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'address' => '654 ABC Street, Cityville',
                'mobile_number' => '0919-876-5432',
                'contact_person' => 'Olivia Wilson',
                'contact_person_number' => '0912-345-6789',
            ],                
            [
                'user_id' => 30,
                'birth_date' => Carbon::parse('1991-11-02'),
                'age' => 31,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '987 DEF Street, Townsville',
                'mobile_number' => '0987-654-3210',
                'contact_person' => 'Ethan Johnson',
                'contact_person_number' => '0919-876-5432',
            ],
        ];

        foreach ($records as $key => $record) {
            Record::create($record);
        }
    }
}
