<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\Models\User;

class CreateStudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2023-203814',
                'grade' => 'Grade 12',
                'course' => 'STEM - IT',
                'section' => 'STEM231',
                'birth_date' => Carbon::parse('2005-01-15'),
                'age' => 18,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'address' => '51 Bonifacio Street, Quezon City',
                'mobile_number' => '0974-923-4570 ',
                'contact_person' => 'Jane Doe',
                'contact_person_number' => '0998-765-4321',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2024-038163',
                'grade' => 'Grade 11',
                'course' => 'STEM - Multi Media',
                'section' => 'STEM244',
                'birth_date' => Carbon::parse('2004-03-15'),
                'age' => 17,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '2772 Roxas Boulevard, Pasay City',
                'mobile_number' => '0927-729-4643 ',
                'contact_person' => 'Sherwin Parker',
                'contact_person_number' => '0987-654-321',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2023-203170',
                'year' => '1st Year',
                'course' => 'STEM - SS',
                'section' => 'SS231',
                'birth_date' => Carbon::parse('1990-01-01'),
                'age' => '33',
                'sex' => 'Male',
                'civil_status' => 'Single',
                'address' => '123 Main Street, City, Country',
                'mobile_number' => '0941-215-7765 ',
                'contact_person' => 'John Doe',
                'contact_person_number' => '0987-654-3210'
            ],
            [
                'name' => 'Masha Scovgachn',
                'email' => 'mscovgachn@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2024-019274',
                'grade' => 'Grade 12',
                'course' => 'ABM',
                'section' => 'ABM241',
                'birth_date' => Carbon::parse('2005-08-10'),
                'age' => '17',
                'sex' => 'Female',
                'civil_status' => 'Single',
                'address' => '123 ABC Street, Cityville',
                'mobile_number' => '0935-765-0839 ',
                'contact_person' => 'Ligaya Scovgachn',
                'contact_person_number' => '0987-654-3210',
            ],
            [
                'name' => 'Eugene Martaho',
                'email' => 'emartaho@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2022-293745',
                'year' => '2nd Year',
                'course' => 'BSCS - IT',
                'section' => 'IT221',
                //'birth_date' => '',
                //'age' => '',
                //'sex' => '',
                //'civil_status' => '',
                //'address' => '',
                //'mobile_number' => '',
                //'contact_person' => '',
                //'contact_person_number' => '',
            ],
            [
                'name' => 'Exia Martinez',
                'email' => 'emartinez@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2021-982642',
                'year' => '3rd Year',
                'course' => 'BSCS - SF',
                'section' => 'SF211',
                //'birth_date' => '',
                //'age' => '',
                //'sex' => '',
                //'civil_status' => '',
                //'address' => '',
                //'mobile_number' => '',
                //'contact_person' => '',
                //'contact_person_number' => '',
            ],
            [
                'name' => 'Anthony Tenrou',
                'email' => 'atenrou@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2025-019273',
                'grade' => 'Grade 11',
                'course' => 'STEM - Engineering',
                'section' => 'STEM252',
            ],
            [
                'name' => 'Jotarou Mandaba',
                'email' => 'jmandaba@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2020-012938',
                'year' => '3rd Year',
                'course' => 'BSCS - SF',
                'section' => 'SF203',
            ],
            [
                'name' => 'Layla Muntaka',
                'email' => 'lmuntaka@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2023-038271',
                'grade' => 'Grade 12',
                'course' => 'STEM - Engineering',
                'section' => 'STEM232',
            ],
            [
                'name' => 'Mia Khalifa',
                'email' => 'mkhalifa@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2021-371947',
                'year' => '2nd Year',
                'course' => 'BSCS - SS',
                'section' => 'SS211',
            ],
            [
                'name' => 'Kensie Karashi',
                'email' => 'kkarashi@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2024-374916',
                'grade' => 'Grade 12',
                'course' => 'ABM',
                'section' => 'ABM242',
            ],
            [
                'name' => 'Natalie Balagtas',
                'email' => 'nbalagtas@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2020-823645',
                'year' => '2nd Year',
                'course' => 'BSCS - IT',
                'section' => 'IT202',
            ],
            [
                'name' => 'Cardo Dalisay',
                'email' => 'cdalisay@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2024-836471',
                'grade' => 'Grade 12',
                'course' => 'ABM',
                'section' => 'ABM243',
            ],
            [
                'name' => 'Hatiro Watakani',
                'email' => 'hwatakani@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2022-174823',
                'year' => '1st Year',
                'course' => 'BSCS - SF',
                'section' => 'SF223',
            ],
            [
                'name' => 'Angelo Mandaro',
                'email' => 'amandaro@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2023-816481',
                'grade' => 'Grade 11',
                'course' => 'STEM - Multi Media',
                'section' => 'STEM234',
            ],
            [
                'name' => 'Summer Candace Mandaline',
                'email' => 'scmandaline@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2021-913746',
                'year' => '1st Year',
                'course' => 'BSCS - SF',
                'section' => 'SF212',
            ],
            [
                'name' => 'Moscov Giovanni',
                'email' => 'mgiovanni@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2023-137569',
                'grade' => 'Grade 11',
                'course' => 'HUMMS',
                'section' => 'HUMMS231',
            ],
            [
                'name' => 'Charles Calambas',
                'email' => 'ccalambas@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2020-203817',
                'year' => '1st Year',
                'course' => 'BSCS - SS',
                'section' => 'SS201',
            ],
            [
                'name' => 'John Carlo Jinjiki',
                'email' => 'jcjinjiki@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2021-237169',
                'grade' => 'Grade 12',
                'course' => 'STEM - Multi Media',
                'section' => 'STEM 215',
            ],
            [
                'name' => 'John Doe',
                'email' => 'jdoe@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '2023-375923',
                'year' => '2nd Year',
                'course' => 'BSCS - SS',
                'section' => 'SS234',
            ],
            /*[
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' =>0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Juan Dela Cruz',
                'email' => 'jdcruz@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayaka Kamisato',
                'email' => 'akamisato@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],
            [
                'name' => 'Ayato Kamisato',
                'email' => 'akamisato2@student.apc.edu.ph',
                'role' => 0,
                'password' => bcrypt('Sample123456'),
                'school_id' => '',
                'year' => '',
                'course' => '',
                'section' => '',
            ],*/
        ];
        foreach ($users as $key => $user) {
            User::create($user);
        }
    }
}
